### ISSUE TITLE
Is there a way to add new jobs on the fly?

### ISSUE THREAD

**Issue by nickbe** [lordmulder/MParallel#5]
Suppose I start the first job - is there a way to keep the job controller running - adding more jobs on the fly -  and in the end stop the controller when I have no more jobs to add?

**Comment by lordmulder** [comment]
Hello.

Well, the list of jobs *can* be read from the standard input (see `--stdin` option). So, in theory, you could pipe in the list of jobs from another program (or script) that generates these jobs "on the fly". As long as the pipe isn't closed, MParallel waits for more jobs and enqueues them as they arrive...

Other than that, there is **no** way.

Sounds like you are looking for a client/server-based batch processing system, where clients submit jobs and the server (eventually) processes these jobs. That's way beyond the scope of MParallel.

Regards
MuldeR

**Comment by nickbe** [comment]
Well yes I've already tried to acomplish this in a batch file, but I didn't come up with mechanism that feeds the pipe and also waits for new jobs to arrive without closing.

Actually I think the correct feature would simply be an option to tell mparallel that it has to look for an already existing controller and re-use it when possible.

That way whatever I feed into mparallel would be put into the same queue.
Imagine a switch to start mparallel with a queue name --queue audioencoder

As long as there's a queue "audioencoder" active the new command would feed the commands into that queue. And if there's no "audioencoder" queue active then a new one is started. And so on.

What do you think about this one?
Cheers
Nick

**Comment by lordmulder** [comment]
Well, as said before, this would require switching to a client/server (master/slave) architecture – which is absolutely **not** what we have right now. Also, and that would probably the biggest work, we would have to implement the *communication* between the "master" and "slave" processes – for example via network port or via a local shared memory region. Synchronization, e.g. via semaphore, would also be required.

Overall, this would **not** be "rocket science" to implement, but it also certainly can **not** be done in 5 minutes. It would require a massive re-write of MParallel. So, I can **not** promise anything...

Regards
MuldeR

**Comment by nickbe** [comment]
Understood. Well currently I solved the problem by creating new jobfile every time I'm adding jobs via batch, then I check if mparallel.exe is already running or not. If so then the second batch quits, while the already running batch restarts mparallel.exe with the next jobfile after it has finished. 

This method works rather well and I'm absolutely fine with it now :)

I saw that someone has asked for an option to have some kind of ETA.
Well maybe an idea would be to let the user define a pattern to look for a progress number in the thread outputs. If you have some kind of bar like this [------ 20%] which is growing then the pattern would be something like "- !PERCENT!%]".

**Comment by nickbe** [comment]
On the other hand a simple ETA in the form of a percentage progress counter could at least be realized by simply counting of the jobs, especially when using a jobfile.

This does not imply a real ETA but at least an overall progress and comparing the running time to the jobs still waiting would at least give a rough idea of the remaining time.

**Comment by nickbe** [comment]
And here's another question for you:
I'm converting audio tracks right now - Storage format MPC of my ripped CDs to M4A for iTunes.
For this I have to read the Audio Tags from the files first and then convert the files by piping them from ffmpeg to qaac which also retags the results.

For this I always have multiple steps per job.
Right now I first read all tags and then I run the conversion itself through the mparallel queue.
Would it be possible to let mparallel work through more than one line per thread. Like having a fixed block of lines per job?   (Example switch: --lines=3 )

**Comment by lordmulder** [comment]
With the **`--shell`** option you should be able to "chain" multiple commands using the **`&&`** operator.

Either that, or just create a Batch file for each job that needs to run multiple sequential commands.

**Comment by nickbe** [comment]
I already solved the problem like that. I didn't realize it would work like this with completely batch jobs that way. Very good indeed.
