### ISSUE TITLE
file path must be ascii ?

### ISSUE THREAD

**Issue by tuwulin365** [lordmulder/MParallel#8]
file path must be ascii ?
![image](https://github.com/lordmulder/MParallel/assets/33275750/cb0a604c-685b-4251-adfa-34fdda98a4d5)

**Comment by lordmulder** [comment]
**MParallel** is fully _Unicode_ (UTF-16) aware (i.e. it uses `wmain()` function and _wide_ strings all the way!), as you can see easily by looking at the source code. So I assume that the program that you are invoking (`avifenc.exe` in your example) uses ANSI strings and therefore can only support characters that exist in your local ANSI Codepage. MParallel can **not** do anything about _that_ 😏 

Did you try to invoke `avifenc.exe` **_directly_**, withe the _Unicode_ file name ???

**Comment by lordmulder** [comment]
Also you may want to try starting `cmd.exe` with the **`/U`** option, if you want to use commands like `dir` 💡 

(In this case, you probable need to pass `--utf16` to `mparallel.exe` too!)

**Comment by tuwulin365** [comment]
It works by using "chcp 65001" in bat file.
